language: c

before_install:
 - sudo apt-get install -qq python-docutils

before_script:
  - apt-get source -q varnish
  - cd varnish*
  - ./configure
  - make
  - cd ..
  - ./autogen.sh
  - ./configure VARNISHSRC=varnish* VMODDIR=`pwd`
  - make

script:
  - make check

